#!/usr/bin/env bash

sbatch dqn/train_cliffwalking_1.sl
sleep .5
sbatch dqn/train_cliffwalking_2.sl
sleep .5
sbatch dqn/train_cliffwalking_3.sl
sleep .5
sbatch dqn/train_cliffwalking_4.sl
sleep .5
sbatch dqn/train_cliffwalking_5.sl
sleep .5
sbatch dqn/train_cliffwalking_6.sl
sleep .5
sbatch dqn/train_cliffwalking_7.sl
sleep .5
sbatch dqn/train_cliffwalking_8.sl
sleep .5
sbatch dqn/train_cliffwalking_9.sl
sleep .5
sbatch dqn/train_cliffwalking_10.sl
sleep .5
sbatch dqn/train_cliffwalking_11.sl
sleep .5
sbatch dqn/train_cliffwalking_12.sl
sleep .5
sbatch dqn/train_cliffwalking_13.sl
sleep .5
sbatch dqn/train_cliffwalking_14.sl
sleep .5
sbatch dqn/train_cliffwalking_15.sl
sleep .5
sbatch dqn/train_cliffwalking_16.sl
sleep .5
sbatch dqn/train_cliffwalking_17.sl
sleep .5
sbatch dqn/train_cliffwalking_18.sl
sleep .5
sbatch dqn/train_cliffwalking_19.sl
sleep .5
sbatch dqn/train_cliffwalking_20.sl
sleep .5
sbatch dqn/train_cliffwalking_21.sl
sleep .5
sbatch dqn/train_cliffwalking_22.sl
sleep .5
sbatch dqn/train_cliffwalking_23.sl
sleep .5
sbatch dqn/train_cliffwalking_24.sl
sleep .5
sbatch dqn/train_cliffwalking_25.sl
sleep .5
sbatch dqn/train_cliffwalking_26.sl
sleep .5
sbatch dqn/train_cliffwalking_27.sl
sleep .5
sbatch dqn/train_cliffwalking_28.sl
sleep .5
sbatch dqn/train_cliffwalking_29.sl
sleep .5
sbatch dqn/train_cliffwalking_30.sl
sleep .5
